site_name: C4G BLIS Support
site_url: https://support.c4gblis.org/
theme:
  name: material
  palette:
    primary: blue
plugins:
  - search:
      enabled: false
extra_css:
  - stylesheets/styles.css